protected/models/Product.php
<?php
/**
 * Created by PhpStorm.
 * User: vovanz
 * Date: 11/25/14
 * Time: 10:18 PM
 */

class Product extends CActiveRecord {
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'product';
    }

    public function rules()
    {
        return array(
            array('product_id', 'safe'),
            array('name', 'safe'),
            array('description', 'safe'),
            array('inet_price', 'safe'),
            array('old_price', 'safe'),
            array('price', 'safe'),
            array('reviews_num', 'safe'),
            array('image_url', 'safe'),
        );
    }

    public function relations()
    {
        return [
            'reviews' => [self::HAS_MANY, 'Review', 'product_id']
        ];
    }
} 

protected/models/Review.php
<?php
/**
 * Created by PhpStorm.
 * User: vovanz
 * Date: 11/25/14
 * Time: 10:18 PM
 */

class Review extends CActiveRecord
{
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        return array(
            array('name,comment', 'required'),
            array('email', 'required'),
            array('email', 'email'),
            array('product_id', 'safe'),
            array('product', 'required'),
        );
    }

    public function tableName()
    {
        return 'review';
    }

    public function relations()
    {
        return [
            'product' => [self::BELONGS_TO, 'Product', 'product_id']
        ];
    }
} 

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

    public function beforeAction($action)
    {
        Yii::app()->clientScript->registerScriptFile('//code.jquery.com/jquery-1.11.0.min.js');
        Yii::app()->clientScript->registerScriptFile('/js/script.js');
        return parent::beforeAction($action);
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     * @param int $page
     */

    public function actionIndex($page = 0)
    {
        if (Yii::app()->request->getPost('onPage')) {
            Yii::app()->session['onPage'] = Yii::app()->request->getPost('onPage');
        }

        if (isset(Yii::app()->session['onPage'])) {
            $onPage = Yii::app()->session['onPage'];
        } else {
            $onPage = '10';
        }

        $products = Product::model()->findAll(array(
            'limit' => $onPage,
            'offset' => $page * intval($onPage)
        ));

        $count = Product::model()->count();
        if (Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('index', ['products' => $products, 'count' => $count, 'onPage' => $onPage]);
        } else {
            $this->render('index', ['products' => $products, 'count' => $count, 'onPage' => $onPage]);
        }
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionProduct($id = 0)
    {
        $product = Product::model()->with('reviews')->findByPk($id);

        if (!$product) {
            throw new CHttpException(404, 'Продукт не найден');
        }

        $comments = $product->reviews;

        $comment_model = new Review();
        $comment_model->product_id = $id;

        $this->render('product', ['product' => $product, 'comments' => $comments, 'comment_model' => $comment_model]);
    }

    /**
     * Displays the contact page
     */
    public function actionReview()
    {
        $comment = new Review();
        $comment->attributes = Yii::app()->request->getPost('Review');
        if ($comment->save()) {
            if (Yii::app()->request->isAjaxRequest) {
                $comments = Review::model()->findAllByAttributes(array('product_id' => $comment->product_id));
                $comment = new Review();
                $this->renderPartial('comments', [
                    'comments' => $comments,
                    'comment_model' => $comment
                ]);
            } else {
                $this->redirect(['site/product']);
            }
        } else {
            $comments = Review::model()->with('product')->findAllByAttributes(array('product_id' => $comment->product_id));
            if (Yii::app()->request->isAjaxRequest) {
                $this->renderPartial('comments', [
                    'comments' => $comments,
                    'comment_model' => $comment
                ]);
            } else {
                $this->render('product', ['product' => $comment->product, 'comments' => $comments, 'comment_model' => $comment]);
            }
        }
    }
}

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div id="page">

	<div id="header">
		<div id="logo"><h1><?php echo CHtml::encode(Yii::app()->name); ?></h1></div>
	</div><!-- header -->

    <div id="content">
        <?php echo $content; ?>
    </div>


	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by 144mln.<br/>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/site/comments.php
<?php if(!empty($comments)) : ?>
    <div class="container">
        <h3>Комментарии</h3>
        <?php foreach($comments as $comment) : ?>
            <div>
                <h4><?php echo $comment['name']; ?></h4>
                <p><?php echo $comment['comment']?></p>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<? $form = $this->beginWidget('CActiveForm'); ?>
<?= $form->hiddenField($comment_model, 'product_id'); ?>
    <div class="container comment-form form">
        <h3>Добавить комментарий</h3>
        <div class="row">
            <?= $form->label($comment_model, 'name')?>
            <?= $form->textField($comment_model, 'name')?>
            <p class="hint">Ведите ваше имя</p>
        </div>
        <div class="row">
            <?= $form->label($comment_model, 'email')?>
            <?= $form->textField($comment_model, 'email')?>
            <p class="hint">Ведите адрес вашей электронной почты</p>
        </div>
        <div class="row">
            <?= $form->label($comment_model, 'comment')?>
            <?= $form->textArea($comment_model, 'comment')?>
            <p class="hint">Ведите ваш комментарий</p>
        </div>
        <div class="row">
            <?=CHtml::ajaxSubmitButton('Отправить', ['site/review'], [
                'update' => '#comments'
            ])?>
        </div>
    </div>
<? $this->endWidget(); ?>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Ошибка';
?>

<div class="container">
    <h2>Ошбика <?php echo $code; ?></h2>
    <div class="error">
        <?php echo CHtml::encode($message); ?>
    </div>
</div>

protected/views/site/index.php
<?php
/* @var $products array */
/* @var $count int */
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<?= CHtml::beginForm('', 'post', ["id" => "on_page_form"]); ?>
<?= CHtml::dropDownList('onPage', $onPage, ['10' => '10','20' => '20','50' => '50']); ?>
<?= CHtml::endForm(); ?>


<?php foreach($products as $product) : ?>
    <div class="container product">
        <div class="product-image">
            <img src="<?php echo $product['image_url']; ?>"/>
        </div>
        <div class="product-data">
            <a href="<?php echo $this->createUrl('product', ['id' =>  $product['id']]); ?>">
                <h3><?php echo $product['name']; ?></h3>
            </a>
            <p>Цена:
                <?php if($product['inet_price'] < $product['old_price']) : ?>
                    <span class="old-price"><?php echo $product['old_price'] ?></span>
                <?php endif; ?>
                <span><?php echo $product['inet_price'] ?></span>
            </p>
            <p>Отзывов: <?php echo $product['reviews_num']; ?></p>
            <p><?php echo $product['description']; ?></p>
        </div>
    </div>
<?php endforeach; ?>

<div class="container pagination">
    <span>Навигация: </span>
    <?php for($i = 0; $i < $count/intval($onPage); $i++) : ?>
        <a href="<?php echo $this->createUrl('index', ['page' => $i]); ?>"><?php echo ($i+1); ?></a>
    <?php endfor; ?>
</div>

<div class="container recent-activity">
    <h3>Недавние действия</h3>
    <?php foreach(Yii::app()->user->getActivity() as $activity) : ?>
        <p><?php echo $activity; ?></p>
    <?php endforeach; ?>
</div>

protected/views/site/product.php
<?php

$this->pageTitle = 'Просмотр товара - ' . $product['name'];
?>

<div class="container product-full">
    <div class="product-image">
        <img src="<?php echo $product['image_url']; ?>"/>
    </div>
    <div class="product-data">
        <h3><?php echo $product['name']; ?></h3>

        <p>Цена:
            <?php if ($product['inet_price'] < $product['old_price']) : ?>
                <span class="old-price"><?php echo $product['old_price'] ?></span>
            <?php endif; ?>
            <span><?php echo $product['inet_price'] ?></span>
        </p>

        <p><?php echo $product['description']; ?></p>
    </div>
</div>

<div id="comments">
    <?php
    $this->renderPartial('comments', [
        'comments' => $comments,
        'comment_model' => $comment_model
    ]);
    ?>
</div>